name: Mirror to gitee

on: [ push ]

# Ensures that only one mirror task will run at a time.
concurrency:
  group: git-mirror

jobs:
  git-mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: wearerequired/git-mirror-action@v1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_DEPLOY_KEY }}
        with:
          source-repo: "git@github.com:Liang34/poster-backend.git"
          destination-repo: "git@gitee.com:liangjianhui_ysn/poster-backend.git"